### ISSUE TITLE
Lane class declaration

### ISSUE THREAD

**Issue by Pharoc** [Pharoc/CarWashProject#18]
I'm getting an error trying to declare a Car c = lane.peek(); in my Gate class.

In the lane class, I used this code in the declaration instead
`public class Lane extends CarQueue<Car> {`
in replacement of 
`public class Lane extends CarQueue {`
and the error went away.

**Comment by sweissman** [comment]
Could cast (Car) to right of equals sign.
.
I'll try to look at code before tonite if I can

**Comment by santiagoa21** [comment]
I'm having this issue too. Did you ever find the solution? I tried the extends CarQueue<Car> but it still does not declare Car c = lane.peek();
